chore(deps): pin dependencies (#2432)
This PR contains the following updates:

| Package | Type | Update | Change | OpenSSF |
|---|---|---|---|---|
| [@orpc/client](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/client))
| dependencies | pin | [`^1.5.2` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fclient/1.5.2/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/client](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/client))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fclient/1.5.1/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/contract](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/contract))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fcontract/1.5.1/1.5.2)
| [![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/openapi](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/openapi))
| dependencies | pin | [`^1.5.2` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fopenapi/1.5.2/1.5.2)
| [![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/openapi](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/openapi))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fopenapi/1.5.1/1.5.2)
| [![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/react-query](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/react-query))
| dependencies | pin | [`^1.5.2` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2freact-query/1.5.2/1.5.2)
| [![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/server](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/server))
| dependencies | pin | [`^1.5.2` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fserver/1.5.2/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/server](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/server))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fserver/1.5.1/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/tanstack-query](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/tanstack-query))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2ftanstack-query/1.5.1/1.5.2)
| [![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/zod](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/zod))
| dependencies | pin | [`^1.5.2` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fzod/1.5.2/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|
| [@orpc/zod](https://orpc.unnoq.com)
([source](https://redirect.github.com/unnoq/orpc/tree/HEAD/packages/zod))
| dependencies | patch | [`1.5.1` ->
`1.5.2`](https://renovatebot.com/diffs/npm/@orpc%2fzod/1.5.1/1.5.2) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/unnoq/orpc/badge)](https://securityscorecards.dev/viewer/?uri=github.com/unnoq/orpc)
|

Add the preset `:preserveSemverRanges` to your config if you don't want
to pin your dependencies.

---

### Release Notes

<details>
<summary>unnoq/orpc (@&#8203;orpc/client)</summary>

###
[`v1.5.2`](https://redirect.github.com/unnoq/orpc/releases/tag/v1.5.2)

[Compare
Source](https://redirect.github.com/unnoq/orpc/compare/v1.5.1...v1.5.2)

##### UndefinedError common schemas
[docs](https://orpc.unnoq.com/docs/openapi/openapi-specification)

`UndefinedError` is used for undefined errors, which is very useful when
using [Type-Safe Error
Handling](https://orpc.unnoq.com/docs/error-handling#type%E2%80%90safe-error-handling).

```ts
const spec = await generator.generate(router, {
  commonSchemas: {
    User: {
      schema: UserSchema,
    },
    UndefinedError: {
      error: 'UndefinedError'
    }
  },
})
```

#####    🚀 Features

- **openapi**: Support UndefinedError in commonSchemas for spec
generation  -  by [@&#8203;unnoq](https://redirect.github.com/unnoq) in
[https://github.com/unnoq/orpc/issues/655](https://redirect.github.com/unnoq/orpc/issues/655)
[<samp>(93fa2)</samp>](https://redirect.github.com/unnoq/orpc/commit/93fa264b)

#####    🐞 Bug Fixes

- **openapi**: Readonly for allowedStrategies and components in
SchemaConverter types  -  by
[@&#8203;unnoq](https://redirect.github.com/unnoq)
[<samp>(8b6cb)</samp>](https://redirect.github.com/unnoq/orpc/commit/8b6cb3ad)

#####     [View changes on
GitHub](https://redirect.github.com/unnoq/orpc/compare/v1.5.1...v1.5.2)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At 12:00 AM through 04:59 AM and 10:00
PM through 11:59 PM, Monday through Friday ( * 0-4,22-23 * * 1-5 ), Only
on Sunday and Saturday ( * * * * 0,6 ) (UTC), Automerge - At any time
(no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/settlemint/asset-tokenization-kit).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC41MC4wIiwidXBkYXRlZEluVmVyIjoiNDAuNTAuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiZGVwZW5kZW5jaWVzIl19-->

Signed-off-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>